// db/03_seed.sql üretir. Prototipteki tohumlu üreticiyi (prototype/src/data.js) Node'da çalıştırır;
// böylece prototip ekranları ile veritabanı aynı müşteri, hesap ve işlemleri gösterir.
// Veri "bugün"e göre son 190 günü kapsar; demodan önce yeniden üretmek için:
//   node db/tools/tohum-uret.mjs  ve ardından  ./db/kur.ps1
import { readFileSync, writeFileSync } from 'node:fs';
import { runInNewContext } from 'node:vm';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const dbKlasoru = join(dirname(fileURLToPath(import.meta.url)), '..');
const kod = readFileSync(join(dbKlasoru, '..', 'prototype', 'src', 'data.js'), 'utf8');
const baglam = { window: {}, console: { info() {}, log: console.log, error: console.error } };
runInNewContext(kod, baglam);
const db = baglam.window.HM.db;
const hata = db.dogrula();
if (hata.hata) throw new Error(`Üretilen veri tutarsız: ${JSON.stringify(hata)}`);

const iki = (n) => String(n).padStart(2, '0');
const metin = (s) => (s == null || s === '' ? 'NULL' : `'${String(s).replace(/'/g, "''")}'`);
const tarih = (d) => `TO_DATE('${d.getFullYear()}-${iki(d.getMonth() + 1)}-${iki(d.getDate())} ${iki(d.getHours())}:${iki(d.getMinutes())}:${iki(d.getSeconds())}', 'YYYY-MM-DD HH24:MI:SS')`;
const zaman = (d) => `TIMESTAMP '${d.getFullYear()}-${iki(d.getMonth() + 1)}-${iki(d.getDate())} ${iki(d.getHours())}:${iki(d.getMinutes())}:${iki(d.getSeconds())}.${String(d.getMilliseconds()).padStart(3, '0')}'`;
const para = (kurus) => (kurus / 100).toFixed(2);
const sayi = (n) => (n == null ? 'NULL' : String(n));

// Satırları PL/SQL bloklarına böler: tek tek round-trip yerine blok başına bir derleme.
// Sıra korunur; bakiye trigger'ı ve CHECK (BAKIYE >= 0) kronolojik sıraya güvenir.
function bloklar(satirlar, boyut = 200) {
  const out = [];
  for (let i = 0; i < satirlar.length; i += boyut) out.push(`BEGIN\n${satirlar.slice(i, i + boyut).join('\n')}\nEND;\n/`);
  return out.join('\n');
}

const hisseler = db.hisseler.map((h) =>
  `INSERT INTO HISSE (HISSE_KODU, AD, TEMSILI_FIYAT) VALUES (${metin(h.kod)}, ${metin(h.ad)}, ${para(h.guncel)});`);

const musteriler = db.musteriler.map((m) =>
  `INSERT INTO MUSTERI (MUSTERI_ID, MUSTERI_NO, AD_SOYAD, EPOSTA, TELEFON, MUSTERI_TIPI, KAYIT_TARIHI, AKTIF) VALUES (${m.id}, ${metin(m.no)}, ${metin(m.ad)}, ${metin(m.eposta)}, ${metin(m.telefon)}, ${metin(m.tip)}, ${tarih(m.kayit)}, ${m.aktif ? 1 : 0});`);

// Hesaplar aktif olarak eklenir (CK_HESAP_PASIF_BAKIYE); pasif olanlar işlemlerden sonra kapatılır.
const hesaplar = db.hesaplar.map((h) =>
  `INSERT INTO HESAP (HESAP_ID, MUSTERI_ID, HESAP_NO, EK_NO, HESAP_TIPI, ACILIS_TARIHI) VALUES (${h.id}, ${h.musteriId}, ${metin(h.no)}, ${h.ek}, ${metin(h.tip)}, ${tarih(h.acilis)});`);

const pasifHesaplar = db.hesaplar.filter((h) => !h.aktif);
const bakiyeli = pasifHesaplar.filter((h) => h.bakiye !== 0);
if (bakiyeli.length) throw new Error(`Bakiyesi sıfır olmayan pasif hesap: ${bakiyeli.map((h) => h.no).join(', ')}`);

const islemler = [...db.islemler].sort((a, b) => a.id - b.id).map((i) =>
  `INSERT INTO ISLEM (ISLEM_ID, HESAP_ID, ISLEM_TIPI, TUTAR, ISLEM_TARIHI, ACIKLAMA, KARSI_HESAP_ID, REFERANS_NO, HISSE_KODU, ADET, BIRIM_FIYAT) VALUES (${i.id}, ${i.hesapId}, ${metin(i.tip)}, ${para(i.tutar)}, ${zaman(i.zaman)}, ${metin(i.aciklama)}, ${sayi(i.karsiHesapId)}, ${metin(i.ref)}, ${metin(i.hisse)}, ${sayi(i.adet)}, ${i.fiyat == null ? 'NULL' : para(i.fiyat)});`);

const simdi = new Date();
const sql = `-- =====================================================================
-- Hesap Masası: tohum veri (OTOMATİK ÜRETİLDİ, elle düzenlemeyin)
-- Üreten: db/tools/tohum-uret.mjs  |  Üretim zamanı: ${simdi.toISOString()}
-- ${db.musteriler.length} müşteri, ${db.hesaplar.length} hesap, ${db.islemler.length} işlem, ${db.hisseler.length} hisse
-- Bakiyeler yazılmaz: ISLEM kayıtları kronolojik sırayla eklenir, trigger bakiyeyi günceller.
-- =====================================================================
${bloklar(hisseler)}
${bloklar(musteriler)}
${bloklar(hesaplar)}
${bloklar(islemler)}
BEGIN
${pasifHesaplar.length ? `    UPDATE HESAP SET AKTIF = 0 WHERE HESAP_ID IN (${pasifHesaplar.map((h) => h.id).join(', ')});\n` : ''}    -- Kimlik kolonları tohum ID'lerinin sonrasından devam etsin
    EXECUTE IMMEDIATE 'ALTER TABLE MUSTERI MODIFY MUSTERI_ID GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE)';
    EXECUTE IMMEDIATE 'ALTER TABLE HESAP MODIFY HESAP_ID GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ISLEM MODIFY ISLEM_ID GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE)';
END;
/
COMMIT;
`;
writeFileSync(join(dbKlasoru, '03_seed.sql'), sql, 'utf8');
console.log(`03_seed.sql yazıldı: ${db.musteriler.length} müşteri, ${db.hesaplar.length} hesap (${pasifHesaplar.length} pasif), ${db.islemler.length} işlem, ${(Buffer.byteLength(sql) / 1024 / 1024).toFixed(1)} MB`);
